
USE 3750-09devnull;

ALTER TABLE USER
ADD CONSTRAINT FK_USER_UserCategoryID
FOREIGN KEY (UserCategoryID) REFERENCES USERCATEGORY(UserCategoryID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE USERDETAIL
ADD CONSTRAINT FK_USERDETAIL_UserID
FOREIGN KEY (UserID) REFERENCES USER(UserID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE USERDETAIL
ADD CONSTRAINT FK_USERDETAIL_DegreeCategoryID
FOREIGN KEY (DegreeCategoryID) REFERENCES DEGREECATEGORY(DegreeCategoryID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE USERDETAIL
ADD CONSTRAINT FK_USERDETAIL_MobileProviderCategoryID
FOREIGN KEY (MobileProviderCategoryID) REFERENCES MOBILEPROVIDERCATEGORY(MobileProviderCategoryID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE USERDETAIL
ADD CONSTRAINT FK_USERDETAIL_CampusCategoryID
FOREIGN KEY (UserID) REFERENCES CAMPUSCATEGORY(CampusCategoryID)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE USERDETAIL
ADD CONSTRAINT FK_USERDETAIL_ReferralCategoryID
FOREIGN KEY (ReferralCategoryID) REFERENCES USER(ReferralCategoryID)
ON UPDATE CASCADE
ON DELETE CASCADE;
